config/routes.rb
Rails.application.routes.draw do
  resources :ticket_tasks
  resources :ticket_messages
  resources :tickets
  resources :ticket_statuses
  resources :ticket_categories
  devise_for :users
  root 'home#index'

end

app/models/ticket_message.rb
class TicketMessage < ActiveRecord::Base
	belongs_to :tickets
end

app/controllers/ticket_messages_controller.rb
class TicketMessagesController < ApplicationController
  before_action :set_ticket_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /ticket_messages
  # GET /ticket_messages.json
  def index
    @ticket_messages = TicketMessage.all
  end

  # GET /ticket_messages/1
  # GET /ticket_messages/1.json
  def show
  end

  # GET /ticket_messages/new
  def new
    @ticket_message = TicketMessage.new
  end

  # GET /ticket_messages/1/edit
  def edit
  end

  # POST /ticket_messages
  # POST /ticket_messages.json
  def create
    @ticket_message = TicketMessage.new(ticket_message_params)

    respond_to do |format|
      if @ticket_message.save
        format.html { redirect_to @ticket_message, notice: 'Ticket message was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_message }
      else
        format.html { render :new }
        format.json { render json: @ticket_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_messages/1
  # PATCH/PUT /ticket_messages/1.json
  def update
    respond_to do |format|
      if @ticket_message.update(ticket_message_params)
        format.html { redirect_to @ticket_message, notice: 'Ticket message was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_message }
      else
        format.html { render :edit }
        format.json { render json: @ticket_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_messages/1
  # DELETE /ticket_messages/1.json
  def destroy
    @ticket_message.destroy
    respond_to do |format|
      format.html { redirect_to ticket_messages_url, notice: 'Ticket message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_message
      @ticket_message = TicketMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_message_params
      params.require(:ticket_message).permit(:ticket_id, :user_id, :content)
    end
end

app/helpers/ticket_messages_helper.rb
module TicketMessagesHelper
end

app/views/ticket_messages/_form.html.erb
<%= simple_form_for(@ticket_message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :ticket_id %>
    <%= f.input :user_id %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_messages/edit.html.erb
<h1>Editing Ticket Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_message %> |
<%= link_to 'Back', ticket_messages_path %>

app/views/ticket_messages/index.html.erb
<h1>Listing Ticket Messages</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_messages.each do |ticket_message| %>
      <tr>
        <td><%= ticket_message.ticket_id %></td>
        <td><%= ticket_message.user_id %></td>
        <td><%= ticket_message.content %></td>
        <td><%= link_to 'Show', ticket_message %></td>
        <td><%= link_to 'Edit', edit_ticket_message_path(ticket_message) %></td>
        <td><%= link_to 'Destroy', ticket_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket message', new_ticket_message_path %>

app/views/ticket_messages/new.html.erb
<h1>New Ticket Message</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_messages_path %>

app/views/ticket_messages/show.html.erb
<p>
  <strong>Ticket:</strong>
  <%= @ticket_message.ticket_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket_message.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @ticket_message.content %>
</p>

<%= link_to 'Edit', edit_ticket_message_path(@ticket_message) %> |
<%= link_to 'Back', ticket_messages_path %>