config/routes.rb
Rails.application.routes.draw do
  resources :ticket_tasks
  resources :ticket_messages
  resources :tickets
  resources :ticket_statuses
  resources :ticket_categories
  devise_for :users
  root 'home#index'

end

app/models/ticket_category.rb
class TicketCategory < ActiveRecord::Base
	has_many :tickets
end

app/controllers/ticket_categories_controller.rb
class TicketCategoriesController < ApplicationController
  before_action :set_ticket_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /ticket_categories
  # GET /ticket_categories.json
  def index
    @ticket_categories = TicketCategory.all
  end

  # GET /ticket_categories/1
  # GET /ticket_categories/1.json
  def show
  end

  # GET /ticket_categories/new
  def new
    @ticket_category = TicketCategory.new
  end

  # GET /ticket_categories/1/edit
  def edit
  end

  # POST /ticket_categories
  # POST /ticket_categories.json
  def create
    @ticket_category = TicketCategory.new(ticket_category_params)

    respond_to do |format|
      if @ticket_category.save
        format.html { redirect_to @ticket_category, notice: 'Ticket category was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_category }
      else
        format.html { render :new }
        format.json { render json: @ticket_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_categories/1
  # PATCH/PUT /ticket_categories/1.json
  def update
    respond_to do |format|
      if @ticket_category.update(ticket_category_params)
        format.html { redirect_to @ticket_category, notice: 'Ticket category was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_category }
      else
        format.html { render :edit }
        format.json { render json: @ticket_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_categories/1
  # DELETE /ticket_categories/1.json
  def destroy
    @ticket_category.destroy
    respond_to do |format|
      format.html { redirect_to ticket_categories_url, notice: 'Ticket category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_category
      @ticket_category = TicketCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_category_params
      params.require(:ticket_category).permit(:name)
    end
end

app/helpers/ticket_categories_helper.rb
module TicketCategoriesHelper
end

app/views/ticket_categories/_form.html.erb
<%= simple_form_for(@ticket_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_categories/edit.html.erb
<h1>Editing Ticket Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_category %> |
<%= link_to 'Back', ticket_categories_path %>

app/views/ticket_categories/index.html.erb
<h1>Listing Ticket Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_categories.each do |ticket_category| %>
      <tr>
        <td><%= ticket_category.name %></td>
        <td><%= link_to 'Show', ticket_category %></td>
        <td><%= link_to 'Edit', edit_ticket_category_path(ticket_category) %></td>
        <td><%= link_to 'Destroy', ticket_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket category', new_ticket_category_path %>

app/views/ticket_categories/new.html.erb
<h1>New Ticket Category</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_categories_path %>

app/views/ticket_categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ticket_category.name %>
</p>

<%= link_to 'Edit', edit_ticket_category_path(@ticket_category) %> |
<%= link_to 'Back', ticket_categories_path %>