config/routes.rb
Rails.application.routes.draw do
  resources :ticket_tasks
  resources :ticket_messages
  resources :tickets
  resources :ticket_statuses
  resources :ticket_categories
  devise_for :users
  root 'home#index'

end

app/controllers/ticket_statuses_controller.rb
class TicketStatusesController < ApplicationController
  before_action :set_ticket_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /ticket_statuses
  # GET /ticket_statuses.json
  def index
    @ticket_statuses = TicketStatus.all
  end

  # GET /ticket_statuses/1
  # GET /ticket_statuses/1.json
  def show
  end

  # GET /ticket_statuses/new
  def new
    @ticket_status = TicketStatus.new
  end

  # GET /ticket_statuses/1/edit
  def edit
  end

  # POST /ticket_statuses
  # POST /ticket_statuses.json
  def create
    @ticket_status = TicketStatus.new(ticket_status_params)

    respond_to do |format|
      if @ticket_status.save
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_status }
      else
        format.html { render :new }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_statuses/1
  # PATCH/PUT /ticket_statuses/1.json
  def update
    respond_to do |format|
      if @ticket_status.update(ticket_status_params)
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_status }
      else
        format.html { render :edit }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_statuses/1
  # DELETE /ticket_statuses/1.json
  def destroy
    @ticket_status.destroy
    respond_to do |format|
      format.html { redirect_to ticket_statuses_url, notice: 'Ticket status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_status
      @ticket_status = TicketStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_status_params
      params.require(:ticket_status).permit(:name)
    end
end

app/helpers/ticket_statuses_helper.rb
module TicketStatusesHelper
end

app/views/ticket_statuses/_form.html.erb
<%= simple_form_for(@ticket_status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_statuses/edit.html.erb
<h1>Editing Ticket Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_status %> |
<%= link_to 'Back', ticket_statuses_path %>

app/views/ticket_statuses/index.html.erb
<h1>Listing Ticket Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_statuses.each do |ticket_status| %>
      <tr>
        <td><%= ticket_status.name %></td>
        <td><%= link_to 'Show', ticket_status %></td>
        <td><%= link_to 'Edit', edit_ticket_status_path(ticket_status) %></td>
        <td><%= link_to 'Destroy', ticket_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket status', new_ticket_status_path %>

app/views/ticket_statuses/new.html.erb
<h1>New Ticket Status</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_statuses_path %>

app/views/ticket_statuses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ticket_status.name %>
</p>

<%= link_to 'Edit', edit_ticket_status_path(@ticket_status) %> |
<%= link_to 'Back', ticket_statuses_path %>