config/routes.rb
Rails.application.routes.draw do
  resources :ticket_tasks
  resources :ticket_messages
  resources :tickets
  resources :ticket_statuses
  resources :ticket_categories
  devise_for :users
  root 'home#index'

end

app/models/ticket_task.rb
class TicketTask < ActiveRecord::Base
	belongs_to :ticket
end

app/controllers/ticket_tasks_controller.rb
class TicketTasksController < ApplicationController
  before_action :set_ticket_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /ticket_tasks
  # GET /ticket_tasks.json
  def index
    @ticket_tasks = TicketTask.all
  end

  # GET /ticket_tasks/1
  # GET /ticket_tasks/1.json
  def show
  end

  # GET /ticket_tasks/new
  def new
    @ticket_task = TicketTask.new
  end

  # GET /ticket_tasks/1/edit
  def edit
  end

  # POST /ticket_tasks
  # POST /ticket_tasks.json
  def create
    @ticket_task = TicketTask.new(ticket_task_params)

    respond_to do |format|
      if @ticket_task.save
        format.html { redirect_to @ticket_task, notice: 'Ticket task was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_task }
      else
        format.html { render :new }
        format.json { render json: @ticket_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_tasks/1
  # PATCH/PUT /ticket_tasks/1.json
  def update
    respond_to do |format|
      if @ticket_task.update(ticket_task_params)
        format.html { redirect_to @ticket_task, notice: 'Ticket task was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_task }
      else
        format.html { render :edit }
        format.json { render json: @ticket_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_tasks/1
  # DELETE /ticket_tasks/1.json
  def destroy
    @ticket_task.destroy
    respond_to do |format|
      format.html { redirect_to ticket_tasks_url, notice: 'Ticket task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_task
      @ticket_task = TicketTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_task_params
      params.require(:ticket_task).permit(:ticket_id, :user_id, :content, :is_done)
    end
end

app/helpers/ticket_tasks_helper.rb
module TicketTasksHelper
end

app/views/ticket_tasks/_form.html.erb
<%= simple_form_for(@ticket_task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :ticket_id %>
    <%= f.input :user_id %>
    <%= f.input :content %>
    <%= f.input :is_done %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_tasks/edit.html.erb
<h1>Editing Ticket Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_task %> |
<%= link_to 'Back', ticket_tasks_path %>

app/views/ticket_tasks/index.html.erb
<h1>Listing Ticket Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>User</th>
      <th>Content</th>
      <th>Is done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_tasks.each do |ticket_task| %>
      <tr>
        <td><%= ticket_task.ticket_id %></td>
        <td><%= ticket_task.user_id %></td>
        <td><%= ticket_task.content %></td>
        <td><%= ticket_task.is_done %></td>
        <td><%= link_to 'Show', ticket_task %></td>
        <td><%= link_to 'Edit', edit_ticket_task_path(ticket_task) %></td>
        <td><%= link_to 'Destroy', ticket_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket task', new_ticket_task_path %>

app/views/ticket_tasks/new.html.erb
<h1>New Ticket Task</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_tasks_path %>

app/views/ticket_tasks/show.html.erb
<p>
  <strong>Ticket:</strong>
  <%= @ticket_task.ticket_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket_task.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @ticket_task.content %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @ticket_task.is_done %>
</p>

<%= link_to 'Edit', edit_ticket_task_path(@ticket_task) %> |
<%= link_to 'Back', ticket_tasks_path %>